apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: fake-gpu-operator
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/run-ai/fake-gpu-operator/fake-gpu-operator
  ref:
    tag: "0.0.81"
