apiVersion: v1
kind: Secret
metadata:
    name: demo-credentials
    namespace: gpu-apps
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:QqMVYIHSXybmyh6ceF4hLTH952zYpXylCA==,iv:Wd/UjMB34YXyv/vC2IeFSYFQwd1aL4dAjWcF9sHDw1g=,tag:SKrAsCvOmIppn0X/NZTW/w==,type:str]
    db-password: ENC[AES256_GCM,data:C9hZWmRG6w==,iv:rDBM/1wjCrgebfgD+OTPra0G870/nQNorJwL8qkCvUg=,tag:1GOXDr5D+HFrAJJXVSZRCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NU9reXQ2VXd5V3JOTnlH
            VmpmaVBYZ3gyNHVoVjQ1NnpKcmlrdUUxN0FzCm1taHVLNG9tcU9RMG1nWkpXeHhH
            NGJMdnA1UTl3ZjZ0TU5oR0JzUFBIQmsKLS0tICt3REpqZitzSEM3Z2c1eStSK1FZ
            aHNqZGFsTVFvRUpSNSs0aUgrSWRnM0UKwO6HI8pXsSIbET/AHYyRI3kELA5AcVIV
            2UhPhbL5jvrf5gjGuN6a4FRJh4fGCWc54mwWYDp2oYXeNeEHrY5v6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u4zkw3fuzlf6rjafrcwphsvl57nlwawue24fehd2mahny946py6s5h9269
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T20:02:14Z"
    mac: ENC[AES256_GCM,data:bxIHVdlvyeaOnPtTZPNw8h+yamO606U3l1Fzs0WFlivax5T/2CXqPgOyQqQ/bQhRuqtJHCYL6OrJ8oKKTVGE0FcJ4YMR00pKpVU0IsNmhHLAcKpJ7QDA02kjM46wMKaq0PbAhJV3s3RhYyMb0MW0jIIXqGNyErqB7jCsQhs4+Qg=,iv:sLzQqP85CwIqVlRcWxxdyLfu1fQmNuEnxG/BRvon62M=,tag:utKzPOUAPJ3orX3Intx7qA==,type:str]
    version: 3.13.1
